/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KART_KART_MSGS_PB_H_INCLUDED
#define PB_KART_KART_MSGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _kart_ActSpeed {
    float speed_mps;
} kart_ActSpeed;

typedef struct _kart_ActAcceleration {
    float lateral_mps2;
    float longitudinal_mps2;
} kart_ActAcceleration;

typedef struct _kart_ActBraking {
    float effort;
} kart_ActBraking;

typedef struct _kart_ActSteering {
    float angle_rad;
    uint32_t raw_encoder;
} kart_ActSteering;

typedef struct _kart_Heartbeat {
    uint32_t uptime_ms;
} kart_Heartbeat;

typedef struct _kart_HealthStatus {
    bool magnet_ok;
    bool i2c_ok;
    bool heap_ok;
    uint32_t agc;
    uint32_t heap_kb;
    uint32_t i2c_errors;
    uint32_t stack_comms;
    uint32_t stack_control;
    uint32_t stack_heartbeat;
    uint32_t stack_health;
} kart_HealthStatus;

typedef struct _kart_TargThrottle {
    float effort;
} kart_TargThrottle;

typedef struct _kart_TargBraking {
    float effort;
} kart_TargBraking;

typedef struct _kart_TargSteering {
    float angle_rad;
} kart_TargSteering;

typedef struct _kart_OrinComplete {
    float throttle;
    float braking;
    float steering_rad;
    uint32_t mission;
    uint32_t machine_state;
    bool shutdown;
} kart_OrinComplete;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define kart_ActSpeed_init_default               {0}
#define kart_ActAcceleration_init_default        {0, 0}
#define kart_ActBraking_init_default             {0}
#define kart_ActSteering_init_default            {0, 0}
#define kart_Heartbeat_init_default              {0}
#define kart_HealthStatus_init_default           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define kart_TargThrottle_init_default           {0}
#define kart_TargBraking_init_default            {0}
#define kart_TargSteering_init_default           {0}
#define kart_OrinComplete_init_default           {0, 0, 0, 0, 0, 0}
#define kart_ActSpeed_init_zero                  {0}
#define kart_ActAcceleration_init_zero           {0, 0}
#define kart_ActBraking_init_zero                {0}
#define kart_ActSteering_init_zero               {0, 0}
#define kart_Heartbeat_init_zero                 {0}
#define kart_HealthStatus_init_zero              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define kart_TargThrottle_init_zero              {0}
#define kart_TargBraking_init_zero               {0}
#define kart_TargSteering_init_zero              {0}
#define kart_OrinComplete_init_zero              {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define kart_ActSpeed_speed_mps_tag              1
#define kart_ActAcceleration_lateral_mps2_tag    1
#define kart_ActAcceleration_longitudinal_mps2_tag 2
#define kart_ActBraking_effort_tag               1
#define kart_ActSteering_angle_rad_tag           1
#define kart_ActSteering_raw_encoder_tag         2
#define kart_Heartbeat_uptime_ms_tag             1
#define kart_HealthStatus_magnet_ok_tag          1
#define kart_HealthStatus_i2c_ok_tag             2
#define kart_HealthStatus_heap_ok_tag            3
#define kart_HealthStatus_agc_tag                4
#define kart_HealthStatus_heap_kb_tag            5
#define kart_HealthStatus_i2c_errors_tag         6
#define kart_HealthStatus_stack_comms_tag        7
#define kart_HealthStatus_stack_control_tag      8
#define kart_HealthStatus_stack_heartbeat_tag    9
#define kart_HealthStatus_stack_health_tag       10
#define kart_TargThrottle_effort_tag             1
#define kart_TargBraking_effort_tag              1
#define kart_TargSteering_angle_rad_tag          1
#define kart_OrinComplete_throttle_tag           1
#define kart_OrinComplete_braking_tag            2
#define kart_OrinComplete_steering_rad_tag       3
#define kart_OrinComplete_mission_tag            4
#define kart_OrinComplete_machine_state_tag      5
#define kart_OrinComplete_shutdown_tag           6

/* Struct field encoding specification for nanopb */
#define kart_ActSpeed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed_mps,         1)
#define kart_ActSpeed_CALLBACK NULL
#define kart_ActSpeed_DEFAULT NULL

#define kart_ActAcceleration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    lateral_mps2,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitudinal_mps2,   2)
#define kart_ActAcceleration_CALLBACK NULL
#define kart_ActAcceleration_DEFAULT NULL

#define kart_ActBraking_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    effort,            1)
#define kart_ActBraking_CALLBACK NULL
#define kart_ActBraking_DEFAULT NULL

#define kart_ActSteering_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_rad,         1) \
X(a, STATIC,   SINGULAR, UINT32,   raw_encoder,       2)
#define kart_ActSteering_CALLBACK NULL
#define kart_ActSteering_DEFAULT NULL

#define kart_Heartbeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,         1)
#define kart_Heartbeat_CALLBACK NULL
#define kart_Heartbeat_DEFAULT NULL

#define kart_HealthStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     magnet_ok,         1) \
X(a, STATIC,   SINGULAR, BOOL,     i2c_ok,            2) \
X(a, STATIC,   SINGULAR, BOOL,     heap_ok,           3) \
X(a, STATIC,   SINGULAR, UINT32,   agc,               4) \
X(a, STATIC,   SINGULAR, UINT32,   heap_kb,           5) \
X(a, STATIC,   SINGULAR, UINT32,   i2c_errors,        6) \
X(a, STATIC,   SINGULAR, UINT32,   stack_comms,       7) \
X(a, STATIC,   SINGULAR, UINT32,   stack_control,     8) \
X(a, STATIC,   SINGULAR, UINT32,   stack_heartbeat,   9) \
X(a, STATIC,   SINGULAR, UINT32,   stack_health,     10)
#define kart_HealthStatus_CALLBACK NULL
#define kart_HealthStatus_DEFAULT NULL

#define kart_TargThrottle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    effort,            1)
#define kart_TargThrottle_CALLBACK NULL
#define kart_TargThrottle_DEFAULT NULL

#define kart_TargBraking_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    effort,            1)
#define kart_TargBraking_CALLBACK NULL
#define kart_TargBraking_DEFAULT NULL

#define kart_TargSteering_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_rad,         1)
#define kart_TargSteering_CALLBACK NULL
#define kart_TargSteering_DEFAULT NULL

#define kart_OrinComplete_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    throttle,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    braking,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    steering_rad,      3) \
X(a, STATIC,   SINGULAR, UINT32,   mission,           4) \
X(a, STATIC,   SINGULAR, UINT32,   machine_state,     5) \
X(a, STATIC,   SINGULAR, BOOL,     shutdown,          6)
#define kart_OrinComplete_CALLBACK NULL
#define kart_OrinComplete_DEFAULT NULL

extern const pb_msgdesc_t kart_ActSpeed_msg;
extern const pb_msgdesc_t kart_ActAcceleration_msg;
extern const pb_msgdesc_t kart_ActBraking_msg;
extern const pb_msgdesc_t kart_ActSteering_msg;
extern const pb_msgdesc_t kart_Heartbeat_msg;
extern const pb_msgdesc_t kart_HealthStatus_msg;
extern const pb_msgdesc_t kart_TargThrottle_msg;
extern const pb_msgdesc_t kart_TargBraking_msg;
extern const pb_msgdesc_t kart_TargSteering_msg;
extern const pb_msgdesc_t kart_OrinComplete_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define kart_ActSpeed_fields &kart_ActSpeed_msg
#define kart_ActAcceleration_fields &kart_ActAcceleration_msg
#define kart_ActBraking_fields &kart_ActBraking_msg
#define kart_ActSteering_fields &kart_ActSteering_msg
#define kart_Heartbeat_fields &kart_Heartbeat_msg
#define kart_HealthStatus_fields &kart_HealthStatus_msg
#define kart_TargThrottle_fields &kart_TargThrottle_msg
#define kart_TargBraking_fields &kart_TargBraking_msg
#define kart_TargSteering_fields &kart_TargSteering_msg
#define kart_OrinComplete_fields &kart_OrinComplete_msg

/* Maximum encoded size of messages (where known) */
#define KART_KART_MSGS_PB_H_MAX_SIZE             kart_HealthStatus_size
#define kart_ActAcceleration_size                10
#define kart_ActBraking_size                     5
#define kart_ActSpeed_size                       5
#define kart_ActSteering_size                    11
#define kart_HealthStatus_size                   48
#define kart_Heartbeat_size                      6
#define kart_OrinComplete_size                   29
#define kart_TargBraking_size                    5
#define kart_TargSteering_size                   5
#define kart_TargThrottle_size                   5

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
