/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "kart_msgs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(kart_ActSpeed, kart_ActSpeed, AUTO)


PB_BIND(kart_ActAcceleration, kart_ActAcceleration, AUTO)


PB_BIND(kart_ActBraking, kart_ActBraking, AUTO)


PB_BIND(kart_ActSteering, kart_ActSteering, AUTO)


PB_BIND(kart_Heartbeat, kart_Heartbeat, AUTO)


PB_BIND(kart_HealthStatus, kart_HealthStatus, AUTO)


PB_BIND(kart_TargThrottle, kart_TargThrottle, AUTO)


PB_BIND(kart_TargBraking, kart_TargBraking, AUTO)


PB_BIND(kart_TargSteering, kart_TargSteering, AUTO)


PB_BIND(kart_OrinComplete, kart_OrinComplete, AUTO)



